# Generated by Django 4.2.30 on 2026-05-03 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_comment_image_comment_parent_thread_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='activitylog',
            name='target',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='target_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='target_type',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('thread_create', 'Thread Created'), ('thread_delete', 'Thread Deleted'), ('thread_hide', 'Thread Hidden'), ('comment_create', 'Comment Created'), ('comment_delete', 'Comment Deleted'), ('comment_hide', 'Comment Hidden'), ('user_update', 'User Info Updated'), ('role_change', 'User Role Changed'), ('report_filed', 'Report Filed')], max_length=32),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['-created_at'], name='forum_activ_created_ed5279_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', '-created_at'], name='forum_activ_user_id_58de53_idx'),
        ),
    ]
