# Generated by Django 4.2.30 on 2026-05-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_comment_is_removed_by_mod_thread_is_removed_by_mod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
